[tool.poetry]
name = "caiasoft-sdk-python"
version = "0.1.0"
description = "SDK for Caiasoft API"
authors = ["Thomas Misilo <tmisilo@ksu.edu>"]
license = "MIT"
readme = "README.md"
packages = [{include = "caiasoft"}]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
