name: Check for No CRLF Line Endings

on:
  push:
    branches:
      - main
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate-crlf-line-endings:
    name: Ensure No crlf Line Endings
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v6.0.0

      - name: Use action to check for CRLF endings
        uses: erclu/check-crlf@master
